create table smoke_session(
ID INT AUTO_INCREMENT,
MEAT VARCHAR(255),
DESCRIPTION VARCHAR(2000),
REFRESH_RATE INT,
TARGET_TEMPERATURE INT,
REFERENCE_THERMOMETER INT,
START_DATE TIMESTAMP,
END_DATE TIMESTAMP
);